import type { Metadata } from "next";
import { Philosopher } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { FloatingNavDemo } from "@/components/Navigation/Header";
import Footer from "@/components/Footer/Footer";

const cinzel = Philosopher({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cinzel.className}>
        <FloatingNavDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
